settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 10 # number of days you want to display in histogram
  collectResponseTimes: false # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'I fucked up...'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jellyfin # unique identifier
    name: Jellyfin
    description: 'The streaming platform' # default=empty
    url: 'https://jellyfin.valentinvie.fr/web/index.html' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: Nextcloud
    name: Nextcloud
    description: 'The cloud platform'
    url: 'https://cloud.valentinvie.fr/login'
    method: GET
    expectStatus: 200

  - id: Ombi
    name: Requests
    description: 'The requests platform'
    url: 'https://requests.valentinvie.fr/'
    method: GET
    expectStatus: 200
