settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: jellyfin # unique identifier
    name: The streaming platform
    #description: 'You write code. They handle the rest.' # default=empty
    url: 'https://jellyfin.valentinvie.fr/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: Nextcloud
    name: The cloud platform
    #description: 'Built for anything connected to the Internet.'
    url: 'https://cloud.valentinvie.fr/'
    method: GET
    expectStatus: 200

  - id: Ombi
    name: The request platform
    url: 'https://requests.valentinvie.fr/'
    method: GET
    expectStatus: 200
